script:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.9.8/terraform_0.9.8_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - terraform init
  - terraform plan -out deploy
  - terraform apply deploy
